"""
models.py
~~~~~~~~~
Pydantic v2 models for the four memory types and the MemoryScope value object.

Every model maps 1-to-1 with the columns in 0002_memory_tables.sql.
The ``embedding`` field stores the vector as a plain ``list[float]``; the
repository layer converts it to/from the Db2 VECTOR representation.

Column type notes:
  - id / *_id  → str (UUID4 generated by default on the Python side)
  - content    → str  (maps to CLOB(65536) in Db2)
  - metadata   → dict (serialized to/from VARCHAR(4096) JSON by the repo)
  - embedding  → list[float] (VECTOR(1536, FLOAT32) NOT NULL, no DB-side
                  default; the application layer always supplies an explicit
                  vector on every INSERT — a real embedding, or a zero-vector
                  sentinel (_zero_vec_str()) when the list is empty).
  - created_at / updated_at / expires_at / deleted_at → datetime | None
  - version    → int  (optimistic concurrency; starts at 1)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# MemoryScope
# ---------------------------------------------------------------------------

class MemoryScope(BaseModel):
    """Hierarchical scoping value object.

    Required on every MemoryStore and repository call.  At minimum,
    ``agent_id`` must be set; the rest are optional but narrow the scope
    further.

    Hierarchy (broadest → narrowest):
        tenant_id (nullable) > agent_id (required) > user_id > thread_id
    """

    tenant_id: str | None = None
    agent_id: str
    user_id: str | None = None
    thread_id: str | None = None

    model_config = {"frozen": True}


# ---------------------------------------------------------------------------
# Shared base
# ---------------------------------------------------------------------------

def _new_uuid() -> str:
    return str(uuid.uuid4())


class _MemoryBase(BaseModel):
    """Common columns present on every memory table row."""

    id: str = Field(default_factory=_new_uuid)

    # Scope columns (mirrors MemoryScope but denormalized into the row
    # so each row is self-contained when returned from a query).
    tenant_id: str | None = None
    agent_id: str
    user_id: str | None = None
    thread_id: str | None = None

    content: str
    metadata: dict[str, Any] = Field(default_factory=dict)

    # embedding is stored as a Python list; the repo converts to/from
    # Db2 VECTOR representation.  An empty list means "not yet embedded";
    # the repo always supplies an explicit vector on INSERT (a real embedding
    # or a zero-vector sentinel) — NOT NULL, no DB-side default in the DDL.
    embedding: list[float] = Field(default_factory=list)

    # confidence: grounding-certainty score for this memory record.
    # 1.0 (default) = fully certain / directly observed.
    # Values below 1.0 indicate derived or inferred records — an LLM-based
    # Consolidator can set 0.6 for a tentative inference vs 0.95 for an
    # explicit user statement.  Persisted as DOUBLE in Db2 (see migration 0003).
    confidence: float = 1.0

    created_at: datetime | None = None
    updated_at: datetime | None = None
    expires_at: datetime | None = None
    version: int = 1
    deleted_at: datetime | None = None

    model_config = {"frozen": False}


# ---------------------------------------------------------------------------
# Memory type models
# ---------------------------------------------------------------------------

class WorkingMemory(_MemoryBase):
    """Raw current-session/thread turn.

    Typically created once per agent message/response pair and kept for
    the duration of the session.  Short-lived: expires_at is usually set
    to a few hours/days after creation.

    Example usage::

        wm = WorkingMemory(
            agent_id="agent-001",
            user_id="user-42",
            thread_id="thread-abc",
            content="User: What's the weather in Tokyo?",
            metadata={"role": "user", "model": "gpt-4o"},
        )
    """


class EpisodicMemory(_MemoryBase):
    """Summarized record of a past run, thread, or event.

    Created by consolidation after a working-memory session ends: the raw
    turns are summarized (by the caller's Consolidator) and stored here as
    a durable narrative the agent can recall in future sessions.

    Example usage::

        ep = EpisodicMemory(
            agent_id="agent-001",
            user_id="user-42",
            content="On 2026-07-30, the user asked about Tokyo weather...",
            metadata={"source_thread": "thread-abc", "summary_model": "gpt-4o"},
        )
    """


class SemanticFact(_MemoryBase):
    """A single extracted fact about an entity or the world.

    Produced by the Consolidator from working/episodic memory.  Each row
    is one atomic, recallable fact.  The ``subject`` and ``predicate``
    pattern is encouraged but not enforced — callers may structure
    ``content`` however they like.

    Example usage::

        fact = SemanticFact(
            agent_id="agent-001",
            user_id="user-42",
            content="User prefers Python over Java.",
            metadata={"confidence": 0.95, "source": "episode-xyz"},
        )
    """


class EntityProfile(_MemoryBase):
    """Aggregated profile for a user or other entity.

    Built by the Consolidator by merging multiple SemanticFacts about the
    same entity into a single dense summary row.  Typically one row per
    (agent_id, user_id) pair; updated rather than re-created.

    Example usage::

        profile = EntityProfile(
            agent_id="agent-001",
            user_id="user-42",
            content="Power Python developer; prefers dark mode; based in Tokyo.",
            metadata={"last_updated_from": "episode-xyz"},
        )
    """


class ProceduralMemory(_MemoryBase):
    """Learned skill, instruction set, or how-to knowledge.

    Typically agent-scoped (user_id / thread_id are often None).  The
    agent recalls these before executing a task class to apply previously
    learned strategies.

    Example usage::

        skill = ProceduralMemory(
            agent_id="agent-001",
            content="When debugging Python, always check the traceback first.",
            metadata={"skill": "debugging", "confidence": 0.9},
        )
    """
